language: go
go:
  - '1.9'
  - '1.10'
  - '1.11'
  - '1.12'

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - $HOME/gopath/src/github.com/hellgate75/vmklet/install-dependancies 
  
script:
  #  - go test -v -cover
  - dep ensure -update
#  - go test -v -cover -gcflags "-N -l" . ...
#  - go install -v -gcflags "-N -l" . ...
#  - $HOME/gopath/bin/goveralls -v -service=travis-ci
  - $HOME/gopath/bin/goveralls -v -insecure -race -show
