language: go
go:
  - '1.9'
  - '1.10'
  - '1.11'
  - '1.12'

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify 
  - go get github.com/pmezard/go-difflib github.com/davecgh/go-spew
  - go get golang.org/x/text/encoding golang.org/x/text/encoding/charmap 
  - go get golang.org/x/text/encoding/htmlindex golang.org/x/text/transform 
  - go get golang.org/x/crypto/ssh/terminal golang.org/x/sys/windows
  - go get golang.org/x/lint github.com/golang/lint github.com/golang/lint/golint

script:
  #  - go test -v -cover
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
