#!/bin/sh
#base tools
go get -u -v github.com/mdempsky/gocode
go get -u -v github.com/golang/lint/golint
go get -u -v golang.org/x/tools/cmd/guru
go get -u -v golang.org/x/tools/cmd/goimports
go get -u -v golang.org/x/tools/cmd/gorename
go get -u github.com/golang/dep/cmd/dep
go get -u -v golang.org/x/lint github.com/golang/lint github.com/golang/lint/golint
#project specific
go get -u -v github.com/stretchr/testify
go get -u -v github.com/pmezard/go-difflib
go get -u -v github.com/davecgh/go-spew
go get -u -v golang.org/x/text/encoding
go get -u -v golang.org/x/text/encoding/charmap
go get -u -v golang.org/x/text/encoding/htmlindex
go get -u -v golang.org/x/text/transform
go get -u -v golang.org/x/crypto/ssh/terminal
go get -u -v golang.org/x/sys/windows
go get -u -v golang.org/x/sys/unix
